//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.PMS.Integration.Data.EF.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMS_IndexList
    {
        public long IndexTypeID { get; set; }
        public string IndexTypeTitle { get; set; }
        public Nullable<System.Guid> IndexId { get; set; }
        public string Title { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> ID_Job { get; set; }
    }
}
