//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.PMS.Integration.Data.EF.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OrganTree
    {
        public string Name_JobTitle { get; set; }
        public int ID { get; set; }
        public string PI { get; set; }
        public int Ind { get; set; }
        public string NodeName { get; set; }
        public Nullable<int> ID_F { get; set; }
        public Nullable<int> NCODE_SERIES { get; set; }
        public Nullable<int> NCODE_TITLE { get; set; }
        public string FullPath { get; set; }
        public Nullable<int> Rasteh { get; set; }
        public Nullable<int> Reshteh { get; set; }
        public string Name_Rasteh { get; set; }
        public string Name_Reshteh { get; set; }
        public Nullable<int> Company_F { get; set; }
        public Nullable<int> NodeType { get; set; }
        public string Name { get; set; }
        public string FamilyName { get; set; }
        public Nullable<int> PersonnelCode { get; set; }
        public Nullable<int> LogUserID { get; set; }
        public string LogActionType { get; set; }
        public Nullable<System.DateTime> LogActionDate { get; set; }
        public string LogComputerName { get; set; }
        public Nullable<bool> IsAgent { get; set; }
        public Nullable<int> PID { get; set; }
        public string FinalPath { get; set; }
        public Nullable<bool> IsInFullPath { get; set; }
        public string Radif { get; set; }
        public Nullable<bool> IsManager { get; set; }
    }
}
