//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.PMS.Presentation.UI.SL.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainAppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainAppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MITD.PMS.Presentation.UI.SL.Assets.Resources.MainAppStrings", typeof(MainAppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information Managment.
        /// </summary>
        public static string BasicInfoManagement {
            get {
                return ResourceManager.GetString("BasicInfoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customfield List.
        /// </summary>
        public static string BasicInfoManagementShowCustomFieldsTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowCustomFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIndex list.
        /// </summary>
        public static string BasicInfoManagementShowJobIndexsTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowJobIndexsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position list.
        /// </summary>
        public static string BasicInfoManagementShowJobPositionsTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowJobPositionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job list.
        /// </summary>
        public static string BasicInfoManagementShowJobsTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log list.
        /// </summary>
        public static string BasicInfoManagementShowLogsTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy list.
        /// </summary>
        public static string BasicInfoManagementShowPliciesTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowPliciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit index management.
        /// </summary>
        public static string BasicInfoManagementShowUnitIndicesTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowUnitIndicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit list.
        /// </summary>
        public static string BasicInfoManagementShowUnitsTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowUnitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group list.
        /// </summary>
        public static string BasicInfoManagementShowUserGroupsTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowUserGroupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        public static string BasicInfoManagementShowUsersTitle {
            get {
                return ResourceManager.GetString("BasicInfoManagementShowUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationCompletedState.
        /// </summary>
        public static string CalculationCompletedState {
            get {
                return ResourceManager.GetString("CalculationCompletedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationInitState.
        /// </summary>
        public static string CalculationInitState {
            get {
                return ResourceManager.GetString("CalculationInitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationNotCompletedState.
        /// </summary>
        public static string CalculationNotCompletedState {
            get {
                return ResourceManager.GetString("CalculationNotCompletedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationPausedState.
        /// </summary>
        public static string CalculationPausedState {
            get {
                return ResourceManager.GetString("CalculationPausedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationRunningState.
        /// </summary>
        public static string CalculationRunningState {
            get {
                return ResourceManager.GetString("CalculationRunningState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationStoppedState.
        /// </summary>
        public static string CalculationStoppedState {
            get {
                return ResourceManager.GetString("CalculationStoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeActiveStatus.
        /// </summary>
        public static string ChangeActiveStatus {
            get {
                return ResourceManager.GetString("ChangeActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAddClaim.
        /// </summary>
        public static string CheckAddClaim {
            get {
                return ResourceManager.GetString("CheckAddClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAssigningJob.
        /// </summary>
        public static string CheckAssigningJob {
            get {
                return ResourceManager.GetString("CheckAssigningJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAssigningJobIndex.
        /// </summary>
        public static string CheckAssigningJobIndex {
            get {
                return ResourceManager.GetString("CheckAssigningJobIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAssigningJobPosition.
        /// </summary>
        public static string CheckAssigningJobPosition {
            get {
                return ResourceManager.GetString("CheckAssigningJobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAssigningUnit.
        /// </summary>
        public static string CheckAssigningUnit {
            get {
                return ResourceManager.GetString("CheckAssigningUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckCancelClaim.
        /// </summary>
        public static string CheckCancelClaim {
            get {
                return ResourceManager.GetString("CheckCancelClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckChangeCalculationDeterministicStatus.
        /// </summary>
        public static string CheckChangeCalculationDeterministicStatus {
            get {
                return ResourceManager.GetString("CheckChangeCalculationDeterministicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckCreatingCalculation.
        /// </summary>
        public static string CheckCreatingCalculation {
            get {
                return ResourceManager.GetString("CheckCreatingCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckCreatingEmployee.
        /// </summary>
        public static string CheckCreatingEmployee {
            get {
                return ResourceManager.GetString("CheckCreatingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckModifingJobIndex.
        /// </summary>
        public static string CheckModifingJobIndex {
            get {
                return ResourceManager.GetString("CheckModifingJobIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckModifyingEmployeeCustomFieldsAndValues.
        /// </summary>
        public static string CheckModifyingEmployeeCustomFieldsAndValues {
            get {
                return ResourceManager.GetString("CheckModifyingEmployeeCustomFieldsAndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckModifyingEmployeeJobPositions.
        /// </summary>
        public static string CheckModifyingEmployeeJobPositions {
            get {
                return ResourceManager.GetString("CheckModifyingEmployeeJobPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckModifyingJobCustomFields.
        /// </summary>
        public static string CheckModifyingJobCustomFields {
            get {
                return ResourceManager.GetString("CheckModifyingJobCustomFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckModifyingJobIndices.
        /// </summary>
        public static string CheckModifyingJobIndices {
            get {
                return ResourceManager.GetString("CheckModifyingJobIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckModifyingJobPositionInquirers.
        /// </summary>
        public static string CheckModifyingJobPositionInquirers {
            get {
                return ResourceManager.GetString("CheckModifyingJobPositionInquirers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckRemovingUnit.
        /// </summary>
        public static string CheckRemovingUnit {
            get {
                return ResourceManager.GetString("CheckRemovingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckReplyClaim.
        /// </summary>
        public static string CheckReplyClaim {
            get {
                return ResourceManager.GetString("CheckReplyClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckSettingInquiryJobIndexPointValue.
        /// </summary>
        public static string CheckSettingInquiryJobIndexPointValue {
            get {
                return ResourceManager.GetString("CheckSettingInquiryJobIndexPointValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckShowingInquirySubject.
        /// </summary>
        public static string CheckShowingInquirySubject {
            get {
                return ResourceManager.GetString("CheckShowingInquirySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My claims.
        /// </summary>
        public static string ClaimSubMenu {
            get {
                return ResourceManager.GetString("ClaimSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimType.
        /// </summary>
        public static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareException.
        /// </summary>
        public static string CompareException {
            get {
                return ResourceManager.GetString("CompareException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteCopyingBasicData.
        /// </summary>
        public static string CompleteCopyingBasicData {
            get {
                return ResourceManager.GetString("CompleteCopyingBasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteInquiry.
        /// </summary>
        public static string CompleteInquiry {
            get {
                return ResourceManager.GetString("CompleteInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteIntializingForInquiry.
        /// </summary>
        public static string CompleteIntializingForInquiry {
            get {
                return ResourceManager.GetString("CompleteIntializingForInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyingStateProgress.
        /// </summary>
        public static string CopyingStateProgress {
            get {
                return ResourceManager.GetString("CopyingStateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyPeriodBasicData.
        /// </summary>
        public static string CopyPeriodBasicData {
            get {
                return ResourceManager.GetString("CopyPeriodBasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotActivatePeriodWhileExistsAnotherActivePeriod.
        /// </summary>
        public static string CouldNotActivatePeriodWhileExistsAnotherActivePeriod {
            get {
                return ResourceManager.GetString("CouldNotActivatePeriodWhileExistsAnotherActivePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotClosePeriodWithOpenClaims.
        /// </summary>
        public static string CouldNotClosePeriodWithOpenClaims {
            get {
                return ResourceManager.GetString("CouldNotClosePeriodWithOpenClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotClosePeriodWithoutAnyDeterministicCalculation.
        /// </summary>
        public static string CouldNotClosePeriodWithoutAnyDeterministicCalculation {
            get {
                return ResourceManager.GetString("CouldNotClosePeriodWithoutAnyDeterministicCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotCompleteInquiryWithNotFilledInquiryForms.
        /// </summary>
        public static string CouldNotCompleteInquiryWithNotFilledInquiryForms {
            get {
                return ResourceManager.GetString("CouldNotCompleteInquiryWithNotFilledInquiryForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotDeleteClaimByAnotherUser.
        /// </summary>
        public static string CouldNotDeleteClaimByAnotherUser {
            get {
                return ResourceManager.GetString("CouldNotDeleteClaimByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotDeleteDeterministicCalculation.
        /// </summary>
        public static string CouldNotDeleteDeterministicCalculation {
            get {
                return ResourceManager.GetString("CouldNotDeleteDeterministicCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotInitializeInquiryForInactivePeriod.
        /// </summary>
        public static string CouldNotInitializeInquiryForInactivePeriod {
            get {
                return ResourceManager.GetString("CouldNotInitializeInquiryForInactivePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotModifyJobIndicesInInquiryStartedState.
        /// </summary>
        public static string CouldNotModifyJobIndicesInInquiryStartedState {
            get {
                return ResourceManager.GetString("CouldNotModifyJobIndicesInInquiryStartedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouldNotStartClaimingWithoutAnyDeterministicCalculation.
        /// </summary>
        public static string CouldNotStartClaimingWithoutAnyDeterministicCalculation {
            get {
                return ResourceManager.GetString("CouldNotStartClaimingWithoutAnyDeterministicCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomFieldType.
        /// </summary>
        public static string CustomFieldType {
            get {
                return ResourceManager.GetString("CustomFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteException.
        /// </summary>
        public static string DeleteException {
            get {
                return ResourceManager.GetString("DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DictionaryName.
        /// </summary>
        public static string DictionaryName {
            get {
                return ResourceManager.GetString("DictionaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoesNotExistAnyActivePeriod.
        /// </summary>
        public static string DoesNotExistAnyActivePeriod {
            get {
                return ResourceManager.GetString("DoesNotExistAnyActivePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoesNotExistAnyDeterministicCalculationInPeriod.
        /// </summary>
        public static string DoesNotExistAnyDeterministicCalculationInPeriod {
            get {
                return ResourceManager.GetString("DoesNotExistAnyDeterministicCalculationInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoesNotExistEvaluationForEmployee.
        /// </summary>
        public static string DoesNotExistEvaluationForEmployee {
            get {
                return ResourceManager.GetString("DoesNotExistEvaluationForEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateException.
        /// </summary>
        public static string DuplicateException {
            get {
                return ResourceManager.GetString("DuplicateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee list.
        /// </summary>
        public static string EmployeeListSubMenu {
            get {
                return ResourceManager.GetString("EmployeeListSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string EmployeeManagementMainMenu {
            get {
                return ResourceManager.GetString("EmployeeManagementMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry subject list.
        /// </summary>
        public static string EmployeesInquiryListSubMenu {
            get {
                return ResourceManager.GetString("EmployeesInquiryListSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmployeesMyInquiryHistorySubMenu {
            get {
                return ResourceManager.GetString("EmployeesMyInquiryHistorySubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Result.
        /// </summary>
        public static string EmployeesMyInquiryResultSubMenu {
            get {
                return ResourceManager.GetString("EmployeesMyInquiryResultSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceedViolationInDeterministicCalculationInPeriod.
        /// </summary>
        public static string ExceedViolationInDeterministicCalculationInPeriod {
            get {
                return ResourceManager.GetString("ExceedViolationInDeterministicCalculationInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishClaiming.
        /// </summary>
        public static string FinishClaiming {
            get {
                return ResourceManager.GetString("FinishClaiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeInquiry.
        /// </summary>
        public static string InitializeInquiry {
            get {
                return ResourceManager.GetString("InitializeInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeInquiryProgress.
        /// </summary>
        public static string InitializeInquiryProgress {
            get {
                return ResourceManager.GetString("InitializeInquiryProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidArgumentException.
        /// </summary>
        public static string InvalidArgumentException {
            get {
                return ResourceManager.GetString("InvalidArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidStateOperationException.
        /// </summary>
        public static string InvalidStateOperationException {
            get {
                return ResourceManager.GetString("InvalidStateOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSumEmployeeWorkTimePercents.
        /// </summary>
        public static string InvalidSumEmployeeWorkTimePercents {
            get {
                return ResourceManager.GetString("InvalidSumEmployeeWorkTimePercents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidUsernameOrPassword.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIndex.
        /// </summary>
        public static string JobIndex {
            get {
                return ResourceManager.GetString("JobIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIndexCategory.
        /// </summary>
        public static string JobIndexCategory {
            get {
                return ResourceManager.GetString("JobIndexCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIndexGroup.
        /// </summary>
        public static string JobIndexGroup {
            get {
                return ResourceManager.GetString("JobIndexGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobPosition.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyForbiddenException.
        /// </summary>
        public static string ModifyForbiddenException {
            get {
                return ResourceManager.GetString("ModifyForbiddenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My work list setting.
        /// </summary>
        public static string MyTasksAccessibilitySettingSubMenu {
            get {
                return ResourceManager.GetString("MyTasksAccessibilitySettingSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodBasicDataCopying.
        /// </summary>
        public static string PeriodBasicDataCopying {
            get {
                return ResourceManager.GetString("PeriodBasicDataCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodClaimingFinishedState.
        /// </summary>
        public static string PeriodClaimingFinishedState {
            get {
                return ResourceManager.GetString("PeriodClaimingFinishedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodClaimingStartedState.
        /// </summary>
        public static string PeriodClaimingStartedState {
            get {
                return ResourceManager.GetString("PeriodClaimingStartedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodClosedState.
        /// </summary>
        public static string PeriodClosedState {
            get {
                return ResourceManager.GetString("PeriodClosedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodInitializeInquiryCompletedState.
        /// </summary>
        public static string PeriodInitializeInquiryCompletedState {
            get {
                return ResourceManager.GetString("PeriodInitializeInquiryCompletedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodInitializingForInquiryState.
        /// </summary>
        public static string PeriodInitializingForInquiryState {
            get {
                return ResourceManager.GetString("PeriodInitializingForInquiryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodInitState.
        /// </summary>
        public static string PeriodInitState {
            get {
                return ResourceManager.GetString("PeriodInitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodInquiryCompletedState.
        /// </summary>
        public static string PeriodInquiryCompletedState {
            get {
                return ResourceManager.GetString("PeriodInquiryCompletedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodInquiryStartedState.
        /// </summary>
        public static string PeriodInquiryStartedState {
            get {
                return ResourceManager.GetString("PeriodInquiryStartedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period List.
        /// </summary>
        public static string PeriodListSubMenu {
            get {
                return ResourceManager.GetString("PeriodListSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Managment.
        /// </summary>
        public static string PeriodManagementMainMenu {
            get {
                return ResourceManager.GetString("PeriodManagementMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance management system.
        /// </summary>
        public static string PMSTitle {
            get {
                return ResourceManager.GetString("PMSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsMainMenu {
            get {
                return ResourceManager.GetString("ReportsMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RollBack.
        /// </summary>
        public static string RollBack {
            get {
                return ResourceManager.GetString("RollBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartClaiming.
        /// </summary>
        public static string StartClaiming {
            get {
                return ResourceManager.GetString("StartClaiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartInquiry.
        /// </summary>
        public static string StartInquiry {
            get {
                return ResourceManager.GetString("StartInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnauthorizedAccessToOperation.
        /// </summary>
        public static string UnauthorizedAccessToOperation {
            get {
                return ResourceManager.GetString("UnauthorizedAccessToOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnExpectedException.
        /// </summary>
        public static string UnExpectedException {
            get {
                return ResourceManager.GetString("UnExpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work List.
        /// </summary>
        public static string WorkListManagement {
            get {
                return ResourceManager.GetString("WorkListManagement", resourceCulture);
            }
        }
    }
}
