//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.PMS.ACL.SSO.UserManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagement.IUserManagementService")]
    public interface IUserManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetRolesForUser", ReplyAction="http://tempuri.org/IUserManagementService/GetRolesForUserResponse")]
        string[] GetRolesForUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetRolesForUser", ReplyAction="http://tempuri.org/IUserManagementService/GetRolesForUserResponse")]
        System.Threading.Tasks.Task<string[]> GetRolesForUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/SetPassword", ReplyAction="http://tempuri.org/IUserManagementService/SetPasswordResponse")]
        void SetPassword(string userName, string password, string oldPassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/SetPassword", ReplyAction="http://tempuri.org/IUserManagementService/SetPasswordResponse")]
        System.Threading.Tasks.Task SetPasswordAsync(string userName, string password, string oldPassWord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementServiceChannel : MITD.PMS.ACL.SSO.UserManagement.IUserManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementServiceClient : System.ServiceModel.ClientBase<MITD.PMS.ACL.SSO.UserManagement.IUserManagementService>, MITD.PMS.ACL.SSO.UserManagement.IUserManagementService {
        
        public UserManagementServiceClient() {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetRolesForUser(string userName) {
            return base.Channel.GetRolesForUser(userName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRolesForUserAsync(string userName) {
            return base.Channel.GetRolesForUserAsync(userName);
        }
        
        public void SetPassword(string userName, string password, string oldPassWord) {
            base.Channel.SetPassword(userName, password, oldPassWord);
        }
        
        public System.Threading.Tasks.Task SetPasswordAsync(string userName, string password, string oldPassWord) {
            return base.Channel.SetPasswordAsync(userName, password, oldPassWord);
        }
    }
}
