//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.PMS.Presentation.BasicInfoApp.Assets.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MITD.PMS.Presentation.BasicInfoApp.Assets.LangResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شغل.
        /// </summary>
        internal static string JobListViewDrgJobListColumnName {
            get {
                return ResourceManager.GetString("JobListViewDrgJobListColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان در لغتنامه.
        /// </summary>
        internal static string JobListViewDrgJobListColumnNameInVocab {
            get {
                return ResourceManager.GetString("JobListViewDrgJobListColumnNameInVocab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست مشاغل.
        /// </summary>
        internal static string JobListViewTitle {
            get {
                return ResourceManager.GetString("JobListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پست ها.
        /// </summary>
        internal static string JobPositionListViewTitle {
            get {
                return ResourceManager.GetString("JobPositionListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JobPositionViewDrgJobPositionListColumnNameInVocab {
            get {
                return ResourceManager.GetString("JobPositionViewDrgJobPositionListColumnNameInVocab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JobPositionViewDrgJobPositionListColumnTitle {
            get {
                return ResourceManager.GetString("JobPositionViewDrgJobPositionListColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string JobViewButtonCancel {
            get {
                return ResourceManager.GetString("JobViewButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره شغل.
        /// </summary>
        internal static string JobViewButtonSave {
            get {
                return ResourceManager.GetString("JobViewButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام در لغتنامه.
        /// </summary>
        internal static string JobViewLabelNameInVocab {
            get {
                return ResourceManager.GetString("JobViewLabelNameInVocab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شغل.
        /// </summary>
        internal static string JobViewLabelTitle {
            get {
                return ResourceManager.GetString("JobViewLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد شغل.
        /// </summary>
        internal static string JobViewTitleCreate {
            get {
                return ResourceManager.GetString("JobViewTitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش شغل.
        /// </summary>
        internal static string JobViewTitleModify {
            get {
                return ResourceManager.GetString("JobViewTitleModify", resourceCulture);
            }
        }
    }
}
